name: Deploy PHP App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          cd /var/www/html
          rm -rf *
          git init
          git remote add origin https://devstroop:TOKEN@github.com/devstroop/perfex_crm.git
          git pull
          composer install --no-dev
          chown -R www-data:www-data *
          service apache2 restart

