name: Deploy PHP App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: '7.3'
    - name: Install dependencies
      run: composer install --no-dev
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          cd /var/www/html
          rm -rf *
          git clone https://github.com/USERNAME/REPO.git .
          composer install --no-dev
          chown -R www-data:www-data *
          service apache2 restart
